In [44]:
import pandas as pd

In [45]:
transacoes = pd.read_csv("data/transacoes.csv", sep=';')

In [46]:
produtos = pd.read_csv("data/produtos.csv", sep=';')

In [47]:
clientes = pd.read_csv("data/clientes.csv", sep=';')

In [48]:
clientes.head()

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697
2,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
3,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
4,0028dda2-334f-40bb-9582-475fb6719471,1,1,1,0,0,1100,2025-10-29 02:08:18.367,2026-02-24 04:49:02.551

In [49]:
clientes.to_json("clientes.json", index=False)

### Copiando os dados do Control + C -> Control + V (arquivo bobo.csv)

In [50]:
df = pd.read_clipboard(sep=',')

In [51]:
df

Empty DataFrame
Columns: [lxml ]
Index: []

### Usando arquivos de páginas HTML

In [ ]:
url = "https://pt.wikipedia.org/wiki/Unidades_federativas_do_Brasil"
estados = pd.read_html(url)
estados

HTTPError: HTTP Error 403: Forbidden

In [53]:
url = "https://pt.wikipedia.org/wiki/Unidades_federativas_do_Brasil"

# Definindo um cabeçalho que simula o Chrome
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

# Lendo as tabelas da página
tabelas = pd.read_html(url, storage_options=headers)

# Geralmente a tabela dos estados é a primeira ou segunda
df_estados = tabelas[1] 
print(df_estados.head())

   Bandeira Unidade federativa Abreviação Sede de governo   Área (km²)  \
0       NaN               Acre         AC      Rio Branco    164 122,2
1       NaN            Alagoas         AL          Maceió     27 767,7
2       NaN              Amapá         AP          Macapá    142 814,6
3       NaN           Amazonas         AM          Manaus  1 570 745,7
4       NaN              Bahia         BA        Salvador    564 692,7

  População (Censo 2022)  Densidade (2005)   PIB (2015)  (% total) (2015)  \
0                830 018               430   13 622 000                 2
1              3 127 683             10861   46 364 000                 8
2                733 759               416   13 861 000                 2
3              3 941 613               205   86 560 000                14
4             14 141 626              2446  245 025 000                41

  PIB per capita (R$) (2015)  IDH (2010) Alfabetização (2016)  \
0                  16 953,46         663                86,9%
1                  13 877,53         631                80,6%
2                  18 079,54         708                  95%
3                  21 978,95         674                93,1%
4                  16 115,89         660                  87%

  Mortalidade infantil (2016) Expectativa de vida (2016)
0                       17,0‰                  73,9 anos
1                       19,5‰                  71,6 anos
2                       23,2‰                  73,9 anos
3                       18,2‰                  71,9 anos
4                       17,3‰                  73,5 anos